// This file is @generated by prost-build.
/// Batch of events for streaming ingestion
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IngestBatch {
    /// Source identifier (e.g., "my-agent", "otel-collector")
    #[prost(string, tag = "1")]
    pub source: ::prost::alloc::string::String,
    /// Cluster/environment identifier
    #[prost(string, tag = "2")]
    pub cluster: ::prost::alloc::string::String,
    /// Either raw bytes (needs plugin transformation) or pre-formatted events
    #[prost(oneof = "ingest_batch::Payload", tags = "3, 4")]
    pub payload: ::core::option::Option<ingest_batch::Payload>,
}
/// Nested message and enum types in `IngestBatch`.
pub mod ingest_batch {
    /// Either raw bytes (needs plugin transformation) or pre-formatted events
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "3")]
        Raw(super::RawPayload),
        #[prost(message, tag = "4")]
        Events(super::EventPayload),
    }
}
/// Raw bytes payload - requires InputPlugin transformation
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RawPayload {
    /// Serialized source-specific format
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// Format hint: "protobuf", "json", "msgpack", etc.
    #[prost(string, tag = "2")]
    pub format: ::prost::alloc::string::String,
}
/// Pre-formatted events - pass-through mode (no transformation)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventPayload {
    #[prost(message, repeated, tag = "1")]
    pub events: ::prost::alloc::vec::Vec<Event>,
}
/// Single event for unary ingestion
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IngestEvent {
    #[prost(string, tag = "1")]
    pub source: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub cluster: ::prost::alloc::string::String,
    /// Format hint for raw payload
    #[prost(string, tag = "5")]
    pub format: ::prost::alloc::string::String,
    #[prost(oneof = "ingest_event::Payload", tags = "3, 4")]
    pub payload: ::core::option::Option<ingest_event::Payload>,
}
/// Nested message and enum types in `IngestEvent`.
pub mod ingest_event {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        /// Raw bytes (needs transformation)
        #[prost(bytes, tag = "3")]
        Raw(::prost::alloc::vec::Vec<u8>),
        /// Pre-formatted event (pass-through)
        #[prost(message, tag = "4")]
        Event(super::Event),
    }
}
/// POLKU's internal event envelope
/// This is what InputPlugins produce and OutputPlugins consume.
/// The payload is opaque bytes - POLKU doesn't interpret it.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Event {
    /// Unique event ID (ULID recommended)
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Unix timestamp in nanoseconds
    #[prost(int64, tag = "2")]
    pub timestamp_unix_ns: i64,
    /// Source that produced this event
    #[prost(string, tag = "3")]
    pub source: ::prost::alloc::string::String,
    /// User-defined event type (e.g., "network", "log")
    #[prost(string, tag = "4")]
    pub event_type: ::prost::alloc::string::String,
    /// Arbitrary key-value metadata
    #[prost(map = "string, string", tag = "5")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// The actual event payload - opaque to POLKU
    #[prost(bytes = "vec", tag = "6")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    /// Optional routing hints for OutputPlugins
    ///
    /// Which outputs to send to (empty = all)
    #[prost(string, repeated, tag = "7")]
    pub route_to: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Acknowledgment response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Ack {
    /// Successfully processed event IDs
    #[prost(string, repeated, tag = "1")]
    pub event_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Errors for failed events
    #[prost(message, repeated, tag = "2")]
    pub errors: ::prost::alloc::vec::Vec<AckError>,
    /// Current buffer size (for backpressure)
    #[prost(int64, tag = "3")]
    pub buffer_size: i64,
    /// Max buffer capacity
    #[prost(int64, tag = "4")]
    pub buffer_capacity: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AckError {
    #[prost(string, tag = "1")]
    pub event_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
/// Health check
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HealthRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthResponse {
    #[prost(bool, tag = "1")]
    pub healthy: bool,
    #[prost(map = "string, message", tag = "2")]
    pub components: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ComponentHealth,
    >,
    #[prost(int64, tag = "3")]
    pub uptime_seconds: i64,
    #[prost(uint64, tag = "4")]
    pub events_processed: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ComponentHealth {
    #[prost(bool, tag = "1")]
    pub healthy: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod gateway_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Gateway service - the main entry point for event ingestion
    #[derive(Debug, Clone)]
    pub struct GatewayClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl GatewayClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> GatewayClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> GatewayClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            GatewayClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Bidirectional streaming for high-throughput event ingestion
        pub async fn stream_events(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::IngestBatch>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::Ack>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/polku.v1.Gateway/StreamEvents",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("polku.v1.Gateway", "StreamEvents"));
            self.inner.streaming(req, path, codec).await
        }
        /// Unary RPC for single event submission
        pub async fn send_event(
            &mut self,
            request: impl tonic::IntoRequest<super::IngestEvent>,
        ) -> std::result::Result<tonic::Response<super::Ack>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/polku.v1.Gateway/SendEvent",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("polku.v1.Gateway", "SendEvent"));
            self.inner.unary(req, path, codec).await
        }
        /// Health check endpoint
        pub async fn health(
            &mut self,
            request: impl tonic::IntoRequest<super::HealthRequest>,
        ) -> std::result::Result<tonic::Response<super::HealthResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/polku.v1.Gateway/Health");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("polku.v1.Gateway", "Health"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod gateway_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with GatewayServer.
    #[async_trait]
    pub trait Gateway: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the StreamEvents method.
        type StreamEventsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::Ack, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Bidirectional streaming for high-throughput event ingestion
        async fn stream_events(
            &self,
            request: tonic::Request<tonic::Streaming<super::IngestBatch>>,
        ) -> std::result::Result<
            tonic::Response<Self::StreamEventsStream>,
            tonic::Status,
        >;
        /// Unary RPC for single event submission
        async fn send_event(
            &self,
            request: tonic::Request<super::IngestEvent>,
        ) -> std::result::Result<tonic::Response<super::Ack>, tonic::Status>;
        /// Health check endpoint
        async fn health(
            &self,
            request: tonic::Request<super::HealthRequest>,
        ) -> std::result::Result<tonic::Response<super::HealthResponse>, tonic::Status>;
    }
    /// Gateway service - the main entry point for event ingestion
    #[derive(Debug)]
    pub struct GatewayServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> GatewayServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for GatewayServer<T>
    where
        T: Gateway,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/polku.v1.Gateway/StreamEvents" => {
                    #[allow(non_camel_case_types)]
                    struct StreamEventsSvc<T: Gateway>(pub Arc<T>);
                    impl<T: Gateway> tonic::server::StreamingService<super::IngestBatch>
                    for StreamEventsSvc<T> {
                        type Response = super::Ack;
                        type ResponseStream = T::StreamEventsStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<tonic::Streaming<super::IngestBatch>>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Gateway>::stream_events(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StreamEventsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/polku.v1.Gateway/SendEvent" => {
                    #[allow(non_camel_case_types)]
                    struct SendEventSvc<T: Gateway>(pub Arc<T>);
                    impl<T: Gateway> tonic::server::UnaryService<super::IngestEvent>
                    for SendEventSvc<T> {
                        type Response = super::Ack;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::IngestEvent>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Gateway>::send_event(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SendEventSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/polku.v1.Gateway/Health" => {
                    #[allow(non_camel_case_types)]
                    struct HealthSvc<T: Gateway>(pub Arc<T>);
                    impl<T: Gateway> tonic::server::UnaryService<super::HealthRequest>
                    for HealthSvc<T> {
                        type Response = super::HealthResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HealthRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Gateway>::health(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = HealthSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for GatewayServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "polku.v1.Gateway";
    impl<T> tonic::server::NamedService for GatewayServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
